spring:
  application:
    name: rft-order-service
  boot:
    admin:
      client:
        url: http://localhost:8888
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: https://${eureka.instance.hostname}:8761/eureka/
ribbon:
  eureka:
    enabled: true